#ifndef LYNX_IR_PLANNER_HPP
#define LYNX_IR_PLANNER_HPP

#include <memory>
#include <string>
#include <vector>
#include <unordered_map>
#include <ast/Node.hpp>
#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>

using namespace LynxAst;

namespace fs = boost::filesystem;

namespace LynxCodegen {

    class IRPlanner {

        private:

            std::vector<std::string> orderedModules;

            std::vector<std::string> sourceFolders;

            std::unordered_map<std::string, std::unique_ptr<Node>> const& moduleAstMap;

            /**
             * @brief Resolves an import name to its corresponding .lynx file path.
             * 
             * Searches all configured source folders to locate the actual file
             * corresponding to a given import statement (e.g., "user/chat_user").
             * Returns a path relative to the root project directory if found.
             *
             * @param importName The module name from the import statement.
             * @return fs::path Resolved relative path to the module file, or empty if not found.
            */
            fs::path resolveImportPath(const std::string& importName);

        public:
            explicit IRPlanner(
                std::vector<std::string> folders,
                const std::unordered_map<std::string, std::unique_ptr<LynxAst::Node>>& moduleMap
            ) : sourceFolders(folders), moduleAstMap(moduleMap) {}

            /**
             * @brief Build a topologically sorted list of modules based on their import dependencies.
             * 
             * Analyzes the module ASTs, extracts import relationships, constructs a dependency graph,
             * and produces a topological ordering to ensure proper compilation order.
            */
            void planModuleOrder();

            /**
             * @brief Retrieve the list of modules sorted in topological order.
             * 
             * The result reflects a compilation-safe order based on import dependencies,
             * as generated by planModuleOrder().
             *
             * @return const reference to a vector of sorted module paths.
            */
            const std::vector<std::string>& getOrderedModules() const;
    };
}

#endif
