/**
 * @file IRPlanner.hpp
 * @brief Declares the IRPlanner class responsible for determining the compilation order of Lynx modules.
 * 
 * The IRPlanner analyzes parsed Lynx AST modules and their import dependencies to generate
 * a topologically sorted list of modules. This ensures that each module is compiled only
 * after all its dependencies have been processed.
 * 
 * **Key Responsibilities:**
 * - Resolves import statements to actual `.lynx` source file paths.
 * - Constructs a dependency graph between modules.
 * - Produces a topologically sorted order of modules for IR generation.
 * - Provides access to the ordered module list for downstream IR generation or linking.
 * 
 * **Used By:**
 * - IRGenerator to orchestrate LLVM IR generation in correct dependency order.
 * - Build system and compiler backend for dependency management.
 * 
 * @author: Ko Thein (Nathan Mratt)
 * @date: November 2, 2024
*/

#ifndef LYNX_IR_PLANNER_HPP
#define LYNX_IR_PLANNER_HPP

#include <memory>
#include <string>
#include <vector>
#include <unordered_map>
#include <ast/Node.hpp>
#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>

using namespace LynxAst;

namespace fs = boost::filesystem;

namespace LynxCodegen {

    class IRPlanner {

        private:

            std::vector<std::string> orderedModules;

            std::vector<std::string> sourceFolders;

            std::unordered_map<std::string, std::unique_ptr<Node>> const& moduleAstMap;

            /**
             * @brief Resolves an import name to its corresponding .lynx file path.
             * 
             * Searches all configured source folders to locate the actual file
             * corresponding to a given import statement (e.g., "user/chat_user").
             * Returns a path relative to the root project directory if found.
             *
             * @param importName The module name from the import statement.
             * @return fs::path Resolved relative path to the module file, or empty if not found.
            */
            fs::path resolveImportPath(const std::string& importName);

        public:
            explicit IRPlanner(
                std::vector<std::string> folders,
                const std::unordered_map<std::string, std::unique_ptr<LynxAst::Node>>& moduleMap
            ) : sourceFolders(folders), moduleAstMap(moduleMap) {}

            /**
             * @brief Build a topologically sorted list of modules based on their import dependencies.
             * 
             * Analyzes the module ASTs, extracts import relationships, constructs a dependency graph,
             * and produces a topological ordering to ensure proper compilation order.
            */
            void planModuleOrder();

            /**
             * @brief Retrieve the list of modules sorted in topological order.
             * 
             * The result reflects a compilation-safe order based on import dependencies,
             * as generated by planModuleOrder().
             *
             * @return const reference to a vector of sorted module paths.
            */
            const std::vector<std::string>& getOrderedModules() const;
    };
}

#endif
