function(target_enable_lto TARGET ENABLE)
    if(NOT ENABLE)
        return()
    endif()

    include(CheckIPOSupported)
    check_ipo_supported(RESULT result OUTPUT output)

    if(result)
        message(STATUS "IPO/LTO is supported for target '${TARGET}'")
        set_property(TARGET "${TARGET}" PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
    else()
        message(WARNING "IPO/LTO is NOT supported: ${output}")
    endif()
endfunction()
