function(add_sanitizer_flags)
    if(NOT ${ENABLE_SANITIZER_ADDRESS} AND NOT ${ENABLE_SANITIZER_UNDEFINED})
        message(STATUS "Sanitizers deactivated")
        return()
    endif()

    if(CMAKE_CXX_COMPILER_ID MATCHES "CLANG" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        add_compile_options("-fno-omit-frame-pointer")
        add_link_options("-fno-omit-frame-pointer")
        
        if(${ENABLE_SANITIZER_ADDRESS})
            add_compile_options("-fsanitize=address")
            add_link_options("-fsanitize=address")
            # set_target_properties(${LYNX_EXECUTABLE} PROPERTIES
            #     ENVIRONMENT "ASAN_OPTIONS=detect_leaks=1:abort_on_error=1")
        endif()
        if(${ENABLE_SANITIZER_UNDEFINED})
            add_compile_options("-fsanitize=undefined")
            add_link_options("-fsanitize=undefined")
        endif()
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        if(${ENABLE_SANITIZER_ADDRESS})
            add_compile_options("/fsanitize=address")
        endif()
        if(${ENABLE_SANITIZER_UNDEFINED})
            message(ERROR "Undefined sanitizer not implemented for MSVC")
        endif()
    else()
        message(ERROR "Compiler not supported for Sanitizers")
    endif()

    # Set ASAN_OPTIONS environment variable for the executable
    # if(${ENABLE_SANITIZER_ADDRESS})
    #     set_target_properties(Lynx PROPERTIES ENVIRONMENT "ASAN_OPTIONS=detect_leaks=1:abort_on_error=1")
    # endif()
endfunction()
