set(JIT_LIB_HEADER_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/IJIT.hpp 
  ${CMAKE_CURRENT_SOURCE_DIR}/MCJITEngine.hpp 
  ${CMAKE_CURRENT_SOURCE_DIR}/ORCJITEngine.hpp 
  ${CMAKE_CURRENT_SOURCE_DIR}/JITFactory.hpp 
  ${CMAKE_CURRENT_SOURCE_DIR}/JITConstants.hpp 
)

set(JIT_LIB_IMMPL_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/impl/MCJITEngine.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/impl/ORCJITEngine.cpp
)

add_library(LynxJIT STATIC ${JIT_LIB_HEADER_SOURCES} ${JIT_LIB_IMMPL_SOURCES})

target_link_libraries(LynxJIT PRIVATE LynxLogger)

target_include_directories(LynxJIT PUBLIC ${LIBRARY_INCLUDES})
